// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  article: defineAsyncComponent(() => import("./Article/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
});
